return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      -- TODO: como adicionar flutter dart aqui
      "lua",
      "vim",
      "vimdoc",
      "json",
      "yaml",
      "markdown",
      "markdown_inline",
      "bash",
      "python",
      "rust",
      "typescript",
      "javascript",
      "tsx",
      "html",
      "css",
      "scss",
      "kotin",
      "gitignore",
      "git_rebase",
      "gitcommit",
      "gitconfig",
      "gitattributes",
    },
  },
}
